export const FETCH_SOME_ASYNC_REQUEST = 'LIST/FETCH_SOME_ASYNC_REQUEST';
export const FETCH_SOME_ASYNC_SUCCEED = 'LIST/FETCH_SOME_ASYNC_SUCCEED';
export const FETCH_SOME_ASYNC_FAILURE = 'LIST/FETCH_SOME_ASYNC_FAILURE';
